eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-exam:
      path: /exam/**
      serviceId: service-exam
    api-user:
      path: /user/**
      serviceId: service-user
  sensitiveHeaders:

