
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  redis:
    database: 0
    host: 39.107.84.0
    port: 6379
    password:
  application:
    name: service-exam
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp149958e5hvnwfazko.mysql.rds.aliyuncs.com:3306/exam_sys
    username: suser
    password: One11111
mybatis:
  type-aliases-package: com.example.demo.entity